sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    access-key-id: LTAI5t7hMczkQC8TzPh68uRq
    access-key-secret: 43U8qgc2mMFCTJB9ImnNYpA2WRAdz0
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: java-sky-take-out-xu
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10